name: AdminTime
main: com.andoutay.admintime.AdminTime
version: 1.2.0
description: >
             AdminTime allows admins to switch in and out of an Admining state and allows them to resume where they left off when done admining
softdepend: [VanishNoPacket, Essentials]

commands:
  admintime:
    description: AdminTime commands
    usage: /<command> [player|list|reload|version|help]. A player name must be specified when entering admin mode! Use /<command> help for more info
    aliases: [at, am, adminmode]

permissions:
  admintime.*:
    description: Gives access to all AdminTime commands
    default: false
    children:
      admintime.notify: true
      admintime.toggle: true
      admintime.reload: true
      admintime.version: true
      admintime.eject: true
      admintime.list: true
      admintime.loginlist: true
  admintime.notify:
    description: Players with this permission are notified when other players enter and exit Admin mode
    default: false
  admintime.toggle:
    description: Allows players to toggle Admin Mode on and off
    default: false
    children:
      admintime.toggle.self: true
      admintime.toggle.others: true
  admintime.toggle.self:
    description: Allows players to toggle Admin Mode to help themselves
    default: false
  admintime.toggle.others:
    description: Allows players to toggle Admin Mode to help other players
    default: false
  admintime.reload:
    description: Allows players to reload the configuration and permissions files
    default: false
  admintime.version:
    description: Allows players to check the version
    default: false
  admintime.eject:
    description: Allows players to remove others from Admin Mode
    default: false
  admintime.list:
    description: Allows players to see who is in Admin Mode
    default: false
  admintime.loginlist:
    description: Shows a list of players in Admin Mode to the player upon logging in
    default: false